-- MySQL Script generated by MySQL Workbench
-- 09/08/15 11:31:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema m108_twitter
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `m108_twitter` ;

-- -----------------------------------------------------
-- Schema m108_twitter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `m108_twitter` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `m108_twitter` ;

-- -----------------------------------------------------
-- Table `m108_twitter`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `m108_twitter`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `m108_twitter`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `nacimiento` DATE NULL,
  `email` VARCHAR(45) NULL,
  `password` TINYTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m108_twitter`.`tweets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `m108_twitter`.`tweets` ;

CREATE TABLE IF NOT EXISTS `m108_twitter`.`tweets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tweet` TINYTEXT NULL,
  `fecha` DATETIME NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tweets_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `m108_twitter`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tweets_usuarios_idx` ON `m108_twitter`.`tweets` (`usuarios_id` ASC);


-- -----------------------------------------------------
-- Table `m108_twitter`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `m108_twitter`.`categorias` ;

CREATE TABLE IF NOT EXISTS `m108_twitter`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m108_twitter`.`tweets_categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `m108_twitter`.`tweets_categorias` ;

CREATE TABLE IF NOT EXISTS `m108_twitter`.`tweets_categorias` (
  `id_tweet` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_tweet`, `id_categoria`),
  CONSTRAINT `fk_tweets_has_categorias_tweets1`
    FOREIGN KEY (`id_tweet`)
    REFERENCES `m108_twitter`.`tweets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tweets_has_categorias_categorias1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `m108_twitter`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tweets_has_categorias_categorias1_idx` ON `m108_twitter`.`tweets_categorias` (`id_categoria` ASC);

CREATE INDEX `fk_tweets_has_categorias_tweets1_idx` ON `m108_twitter`.`tweets_categorias` (`id_tweet` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
