-- MySQL Script generated by MySQL Workbench
-- 09/17/15 11:38:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema excusas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema excusas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `excusas` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `excusas` ;

-- -----------------------------------------------------
-- Table `excusas`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `excusas`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `excusas`.`uso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `excusas`.`uso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_excusa` INT NULL,
  `fecha_uso` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `excusas`.`excusas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `excusas`.`excusas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `excusa` TINYTEXT NULL,
  `id_categoria` INT NOT NULL,
  `id_uso` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_excusas_categorias_idx` (`id_categoria` ASC),
  INDEX `fk_excusas_uso1_idx` (`id_uso` ASC),
  CONSTRAINT `fk_excusas_categorias`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `excusas`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_excusas_uso1`
    FOREIGN KEY (`id_uso`)
    REFERENCES `excusas`.`uso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
